### ISSUE TITLE
Insert check for edit-mode inside ListViewExt 

### ISSUE THREAD

**Issue by shomeser** [shamanland/xdroid#3]
```
 Rendering Problems The following classes could not be instantiated:
- xdroid.widget.ListViewExt (Open Class, Show Exception)
 Tip: Use View.isInEditMode() in your custom views to skip code or show sample data when shown in the IDE  Exception Details java.lang.ClassNotFoundException: null.favorites.InstrumentBinder  
 at java.lang.ClassLoader.loadClass(ClassLoader.java:424)  
 at java.lang.ClassLoader.loadClass(ClassLoader.java:357)  
 at java.lang.Class.forName0(Class.java:-2)  
 at java.lang.Class.forName(Class.java:260)  
 at xdroid.core.ReflectUtils.newInstanceByClassName 
  ... (ReflectUtils.java:288)  
 at xdroid.widget.ListViewExt.initAdapter(ListViewExt.java:120)  
 at xdroid.widget.ListViewExt.initAdapter(ListViewExt.java:134)  
 at xdroid.widget.ListViewExt.init(ListViewExt.java:84)  
 at xdroid.widget.ListViewExt.<init>(ListViewExt.java:52)  
 at java.lang.reflect.Constructor.newInstance(Constructor.java:408)  
 at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:806)  
 at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:64)  
 at android.view.LayoutInflater.rInflate(LayoutInflater.java:782)  
 at android.view.LayoutInflater.inflate(LayoutInflater.java:504)  
 at android.view.LayoutInflater.inflate(LayoutInflater.java:385) Copy stack to clipboard
```

**Comment by shomeser** [comment]
Done in 0.0.14
